name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Linting
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pylint **/*.py

    - name: Run tests
      run: |
        pytest ./src/test.py